FROM golang:1.25.1 as dep
COPY dep /binary /
ENTRYPOINT [ "/opt/app/run.sh --port 8080" ]
ENTRYPOINT [ "/opt/app/run.sh --port 8080" ]

FROM alpine:3.13
USER mike
ENTRYPOINT [ "/opt/app/run.sh --port 8080" ]