FROM golang:1.23.5 AS builder
RUN command CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:3.13
COPY --from=builder /go/src/github.com/alexellis/href-counter/app .
USER mike
CMD ./app